component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/dom/.*
- ./bin/dom/traversal/.*
- ./bin/dom/wrappers/.*
- ./bin/jaxp/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/html/.*
- ./bin/org/apache/html/dom/.*
- ./bin/org/apache/wml/.*
- ./bin/org/apache/wml/dom/.*
- ./bin/org/apache/xerces/.*
- ./bin/org/apache/xerces/dom/.*
- ./bin/org/apache/xerces/dom/events/.*
- ./bin/org/apache/xerces/dom3/.*
- ./bin/org/apache/xerces/dom3/as/.*
- ./bin/org/apache/xerces/impl/.*
- ./bin/org/apache/xerces/impl/dtd/.*
- ./bin/org/apache/xerces/impl/dtd/models/.*
- ./bin/org/apache/xerces/impl/dv/.*
- ./bin/org/apache/xerces/impl/dv/dtd/.*
- ./bin/org/apache/xerces/impl/dv/util/.*
- ./bin/org/apache/xerces/impl/dv/xs/.*
- ./bin/org/apache/xerces/impl/io/.*
- ./bin/org/apache/xerces/impl/msg/.*
- ./bin/org/apache/xerces/impl/validation/.*
- ./bin/org/apache/xerces/impl/xpath/.*
- ./bin/org/apache/xerces/impl/xpath/regex/.*
- ./bin/org/apache/xerces/impl/xs/.*
- ./bin/org/apache/xerces/impl/xs/identity/.*
- ./bin/org/apache/xerces/impl/xs/models/.*
- ./bin/org/apache/xerces/impl/xs/opti/.*
- ./bin/org/apache/xerces/impl/xs/traversers/.*
- ./bin/org/apache/xerces/impl/xs/util/.*
- ./bin/org/apache/xerces/jaxp/.*
- ./bin/org/apache/xerces/jaxp/datatype/.*
- ./bin/org/apache/xerces/jaxp/validation/.*
- ./bin/org/apache/xerces/parsers/.*
- ./bin/org/apache/xerces/stax/.*
- ./bin/org/apache/xerces/stax/events/.*
- ./bin/org/apache/xerces/util/.*
- ./bin/org/apache/xerces/xinclude/.*
- ./bin/org/apache/xerces/xni/.*
- ./bin/org/apache/xerces/xni/grammars/.*
- ./bin/org/apache/xerces/xni/parser/.*
- ./bin/org/apache/xerces/xpointer/.*
- ./bin/org/apache/xerces/xs/.*
- ./bin/org/apache/xerces/xs/datatypes/.*
- ./bin/org/apache/xml/.*
- ./bin/org/apache/xml/serialize/.*
- ./bin/org/w3c/.*
- ./bin/org/w3c/dom/.*
- ./bin/org/w3c/dom/html/.*
- ./bin/sax/.*
- ./bin/sax/helpers/.*
- ./bin/simpletype/.*
- ./bin/socket/.*
- ./bin/socket/io/.*
- ./bin/ui/.*
- ./bin/xni/.*
- ./bin/xni/parser/.*
- ./bin/xs/.*
- ./data/.*
- ./docs/.*
- ./docs/dtd/.*
- ./docs/style/.*
- ./docs/style/graphics/.*
- ./docs/style/stylesheets/.*
- ./lib/.*
- ./samples/.*
- ./samples/dom/.*
- ./samples/dom/traversal/.*
- ./samples/dom/wrappers/.*
- ./samples/jaxp/.*
- ./samples/sax/.*
- ./samples/sax/helpers/.*
- ./samples/simpletype/.*
- ./samples/socket/.*
- ./samples/socket/io/.*
- ./samples/ui/.*
- ./samples/xni/.*
- ./samples/xni/parser/.*
- ./samples/xs/.*
